branches:
  except:
    - /^v\d+\.\d+\.\d+(-(alpha|beta)\.\d+(@(alpha|beta))?)?$/

before_install:
  - curl ifconfig.co

jobs:
  include:
    - stage: release
      node_js: 12
      script: skip
      before_deploy: npm install semantic-release @traverson/semantic-release-config --no-save
      deploy:
        provider: script
        edge: true
        script: npx semantic-release
        on:
          all_branches: true
