import:
  - form8ion/.travis-ci:semantic-release-tag-exclusion.yml

before_install:
  - curl ifconfig.co

jobs:
  include:
    - stage: release
      node_js: 12
      script: skip
      before_deploy: npm install semantic-release @traverson/semantic-release-config --no-save
      deploy:
        provider: script
        edge: true
        script: npx semantic-release
        on:
          all_branches: true
